name: First Workflow

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World
        run: echo "Hello GitHub Actions 🚀"
